In [1]:
import pandas as pd

In [2]:
# Read preprocessed data
df = pd.read_csv("citation_data_complete.csv")

In [3]:
display(df)

,ticket_number,issue_date,issue_time,rp_state_plate,plate_expiry_date,make,body_style,color,location,route,...,fine_amount,agency_desc,color_desc,body_style_desc,violation_code,violation_description,meter_id,marked_time,lat,lon
0,4508182571,2020-01-01,228,CA,NaN,VOLK,PA,BK,1729 CLINTON ST,00600,...,68.0,56 - DOT - CENTRAL,BLACK,PASSENGER CAR,80.61,STANDNG IN ALLEY,NaN,NaN,34.072180,-118.262252
1,4508195565,2020-01-01,736,CA,NaN,NISS,PA,GY,700 76TH ST W,00500,...,68.0,55 - DOT - SOUTHERN,GREY,PASSENGER CAR,22514,FIRE HYDRANT,NaN,NaN,33.970746,-118.285640
2,1109775155,2020-01-01,100,CA,202002.0,DODG,PA,BL,328 LORENA,NaN,...,68.0,WESTERN,BLUE,PASSENGER CAR,22500F,NaN,NaN,NaN,34.034616,-118.196633
3,1110713262,2020-01-01,1830,CA,201909.0,NISS,PA,BK,2800 E OBSERVATORY,NaN,...,68.0,HOLLYWOOD,BLACK,PASSENGER CAR,22514,NaN,NaN,NaN,34.123408,-118.302409
4,1110713273,2020-01-01,1900,CA,NaN,FORD,PA,GY,2800 E OBSERVATORY,NaN,...,68.0,HOLLYWOOD,GREY,PASSENGER CAR,22514,NaN,NaN,NaN,34.123408,-118.302409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993675,4563783313,2023-03-27,2131,CA,202302.0,VOLK,PA,WT,2118 6TH AVE,0205B,...,68.0,51 - DOT - WESTERN,WHITE,PASSENGER CAR,22500E,BLOCKING DRIVEWAY,NaN,0.0,34.037828,-118.323630
4993676,4564468904,2023-03-27,2051,CA,0.0,MERZ,PA,WT,3901 BLUE CANYON DR,350R1,...,68.0,53 - DOT - VALLEY,WHITE,PASSENGER CAR,80.58L,PREFERENTIAL PARKING,NaN,0.0,34.138853,-118.385230
4993677,4563965055,2023-03-27,2227,CA,202401.0,TOYT,PA,BK,15202 VICTORY BLVD,NaN,...,68.0,53 - DOT - VALLEY,BLACK,PASSENGER CAR,80.61,STANDNG IN ALLEY,NaN,0.0,34.186651,-118.464072
4993678,4564298384,2023-03-27,2123,CA,202004.0,NISS,VN,WT,600 PARK ROW DR,NaN,...,73.0,56 - DOT - CENTRAL,WHITE,VAN,80.69B,NO PARKING,NaN,0.0,34.076598,-118.231198
4993679,4564603212,2023-03-27,2115,CA,202304.0,CHEV,PA,SL,2331 KELTON AVE,0203A,...,68.0,51 - DOT - WESTERN,SILVER,PASSENGER CAR,80.58L,PREFERENTIAL PARKING,NaN,0.0,34.040672,-118.431690

# Analysis on Violation Code

In [4]:
unique_violation = df['violation_code'].unique()
print("Number of unique violation code: ", len(unique_violation))

Number of unique violation code:  342

In [5]:
print(unique_violation)

['80.61' '22514' '22500F' '4000A1' '22500H' '572521D' '8803A' '8069A'
 '5200A' '8606' '8603' '8069AA' '8069B' '4000A' '8056E4' '22500E' '8056E2'
 '5204A' '8939' '80714' '6344K2' '8936' '17104H' '80.56E1' '80.56E4+'
 '80.69B' '80.69AA+' '80.69A+' '80.56E2' '80.69.2' '5204A-' '22500A'
 '22507.8A-' '21211B' '88.66' '22502A' '5200' '80.53' '22511.1B' '80.73.2'
 '80.71.3' '6344K7' '22522-' '22500C' '80.58L' '80.69.1A' '22500I-'
 '22500B' '80.69AP+' '22507.8C2' '22500L-' '80.71.4' '6344K8' '22502E'
 '80.66.1D' '88.13B+' '8058L' '225078A' '57490884' '225118' '80691A'
 '8056E1' '8053' '22500I' '80.7' '80.69BS' '80.56E3' '88.03A' '80.70'
 '88.63B+' '22500D' '80.69C' '21113A+' '22507.8C1' '22500.1+' '80.49+'
 '80.54H1' '88.53' '88.64A' '80.69.4' '22511.57C' '80.58.1' '8061'
 '52011C' '80732' '80731' '8813B' '22511.57B' '80.69.1C' '80.69D' '22526'
 '22500' '22500E1' '8070' '80713' '80713*' '80694**' '80694*' '80694'
 '80581' '8069AP' '21113' '80.75.1' '5204' '8069C' '8755' '8069BS' '8049'
 '89391C' '8940' '22507.8B-' '225078' '80703' '22651D' '26708A1' '80691'
 '17104C' '5200B' '80692**' '8606B' '22522' '22502' '225078C1' '86.03'
 '80.74' '22511.56B' '8709H' '8709B' '8396' '52011' '225001' '89391B'
 '5402' '22400A' '80692' '225078C2' '86.06' '22658H' '225078B' '8056E3'
 '2251157A' '8603A' '22515' '8501' '80.72' '22511.57A' '22651K' '8813A'
 '572521E' '80.54' '22500K' '5201F' '8063B' '22521' '6393H' '8803' '5201A'
 '2251157B' '57940884' '26710' '8938' '80.73.1+' '8866' '8071B' '21113A'
 '80518' '80661D' '8704' '22523B-' '22651B' '22523B' '80692*' '87.55'
 '5749088' '2257157B' '12500B' '85.01' '8501A' '52011A' '226500H' '8813'
 '80691C' '22502C' '5200A1' '80.72.5' '21210' '8613A' '8863A' '22500J'
 '5201D' '8863B' '8863' '21458A1' '8069' '8051A' '89311B' '80749' '6344K'
 '80704' '8074' '81714' '6644K9' '6344B14' '22500L' '87.54' '8940B' '4171'
 '8056E' '4000' '8602' '8056E4#' '8069A#' '22500I#' '22651' '22500G'
 '22651H' '572522E' '6806' '22502A2' '8049A' '8940A' '8440A' '22651N'
 '8816A' '89391A' '8073' '22507A' '70803' '21209B' '8942' '8711' '5204C'
 '22669A' '22656' '6344B14C' '8055A3' '5202' '21113A1' '21970A' '6803'
 '4463C' '8960' '63447' '63442' '80741' '22550H' '22650H' '8702' '8709C'
 '22507' '8001A' '80361A' '5201B' '6344' '2251157C' '8709' '807104'
 '22658' '5204A1' '63K44' '80714B' '22511' '8056' '6644K2' '8605' '8501B'
 '8853' '22505' '5006' '80361' '8306' '22512A' '8709D' '8946' '5201G'
 '8709A' '80651' '22520' '8709K' '2250' '8053E1' '5604A' '22651E' '40001A'
 '22400' '22400H' '6344KR' '272521E' '87.53' '8055A2' '22523A' '2500'
 '225022' '2251156B' '8054H1' '21211D' '8003A' '226510' '80733' '574908'
 '52001A' '13' '5402A' '88661' '221157B' '4462B' '26708' '22502B' '21211A'
 '5201B1' '4204' '80692A' '8363' '40004A' '8072' '80715' '80661' '225013'
 '80701' '520F' '5206A' '5201C' '8866A2' '80722' '8943' '8866A1' '6347K7'
 '2608A' '80561' '8606H' '80692A1' '6344C' '80736' '27211B' '25200B'
 '22651J' '80.56E2Z' '80751' '014' '000' '80.73B2.F' '4000(a)1']

In [6]:
# Create a dataframe with only valid violation description
work_df = df[df['violation_description'].notna()]

In [7]:
%%time
# Obtain dictionary for each unique violation code
violation_dict = dict()
for code in unique_violation:
    try:
        description = work_df.loc[work_df['violation_code'] == code, 'violation_description'].iloc[0]
        violation_dict[code] = description
    except:
        violation_dict[code] = ''

Wall time: 55.2 s

In [8]:
# Preview of dictionary
# {k: violation_dict[k] for k in list(violation_dict)}

In [9]:
# Keep key-value pair with violation description
valid_violation_dict = {k: v for k, v in violation_dict.items() if v}
{k: valid_violation_dict[k] for k in list(valid_violation_dict)}

{'80.61': 'STANDNG IN ALLEY',
 '22514': 'FIRE HYDRANT',
 '22500F': 'PARKED ON SIDEWALK',
 '22500H': 'DOUBLE PARKING',
 '22500E': 'BLOCKING DRIVEWAY',
 '6344K2': 'NO PARKING BETWEEN POSTED HOURS',
 '80.56E1': 'WHITE ZONE',
 '80.56E4+': 'RED ZONE',
 '80.69B': 'NO PARKING',
 '80.69AA+': 'NO STOP/STAND',
 '80.69A+': 'STOP/STAND PROHIBIT',
 '80.56E2': 'YELLOW ZONE',
 '80.69.2': 'COMM VEH OVER TIME LIMIT',
 '5204A-': 'DISPLAY OF TABS',
 '22500A': 'WITHIN INTERSECTION',
 '22507.8A-': 'DISABLED PARKING/NO DP ID',
 '21211B': 'BLK BIKE PATH OR LANE',
 '88.66': 'ELECTRIC CHARGING STATION SPACES',
 '22502A': '18 IN. CURB/2 WAY',
 '5200': 'DISPLAY OF PLATES',
 '80.53': 'PARKED IN PARKWAY',
 '22511.1B': 'PRK IN ELEC VEH SPACE',
 '80.73.2': 'EXCEED 72HRS-ST',
 '80.71.3': 'PARKING/FRONT YARD',
 '6344K7': 'PARKING OUTSIDE PARKING STALLS',
 '22522-': '3 FT. SIDEWALK RAMP',
 '22500C': 'SAFETY ZONE/CURB',
 '80.58L': 'PREFERENTIAL PARKING',
 '80.69.1A': 'COMM TRAILER/22 FT.',
 '22500I-': 'PARKED IN BUS ZONE',
 '22500B': 'PARKED IN CROSSWALK',
 '80.69AP+': 'NO STOP/STANDING',
 '22507.8C2': 'DISABLED PARKING/CROSS HATCH',
 '22500L-': 'DP-BLKNG ACCESS RAMP',
 '80.71.4': 'PRIVATE PROPERTY',
 '6344K8': 'SIGN POSTED - NO PARKING',
 '22502E': '18 IN. CURB/1 WAY',
 '80.66.1D': 'RESTRICTED TAXI ZONE',
 '88.13B+': 'METER EXP.',
 '80.7': 'NO STOPPING/ANTI-GRIDLOCK ZONE',
 '80.69BS': 'NO PARK/STREET CLEAN',
 '80.56E3': 'GREEN ZONE',
 '88.03A': 'OUTSIDE LINES/METER',
 '80.70': 'NO STOPPING/ANTI-GRIDLOCK ZONE',
 '88.63B+': 'OFF STR/OVERTIME/MTR',
 '22500D': 'PK-15FT FIRE ST',
 '80.69C': 'PARKED OVER TIME LIMIT',
 '21113A+': 'PUBLIC GROUNDS',
 '22507.8C1': 'DISABLED PARKING/BOUNDARIES',
 '22500.1+': 'PARKED IN FIRE LANE',
 '80.49+': '18 IN/CURB/COMM VEH',
 '80.54H1': 'OVNIGHT PRK W/OUT PE',
 '88.53': 'OFF STR MTR/OUT LINE',
 '88.64A': 'TIME LIMIT/CITY LOT',
 '80.69.4': 'PK OVERSIZ',
 '22511.57C': 'DP-ALTERED',
 '80.58.1': 'CARSHARE PARKING',
 '8813B': 'METER EXPIRED',
 '22511.57B': 'DP- RO NOT PRESENT',
 '80.69.1C': 'PK TRAILER',
 '80.69D': "VEH/LOAD OVR 6' HIGH",
 '22526': 'BLOCKING INTERSECTION',
 '80.75.1': 'AUDIBLE ALARM',
 '22507.8B-': 'DISABLED PARKING/OBSTRUCT ACCESS',
 '86.03': 'CITY PARK/PROHIB',
 '80.74': 'CLEANING VEH/STREET',
 '22511.56B': 'DP-REFUSE ID',
 '86.06': 'CITY PARK/PROHIB',
 '22515': 'UNATT/MOTOR ON',
 '80.72': 'RED FLAG DAY',
 '22511.57A': 'DP-SUBPLATE',
 '80.54': 'OVERNIGHT PARKING',
 '22500K': 'PARKED ON BRIDGE',
 '22521': 'ON RR TRACK/7.5 FT',
 '80.73.1+': 'STORING VEH/ON STR',
 '22523B-': 'ABAND VEH/PUB/PRIV',
 '87.55': 'FOR SALE SIGN',
 '85.01': 'REPAIRING VEH/STREET',
 '80.72.5': 'PK ON PRIV ST',
 '21210': 'BICYCLE PARKING',
 '22500J': 'PARKNG IN TUNNEL',
 '87.54': 'ADVERTISING ON VEH',
 '22500G': 'OBSTR EXCAVATN',
 '22507A': 'OVERSIZED VEHICLE PARKING TOPHAM ST',
 '87.53': 'MOB BILBD ADV DISP',
 '80.56E2Z': 'ZERO-EMISSION ZONE',
 '014': '22500I',
 '000': '8009H',
 '80.73B2.F': 'CATERING VIOLATION',
 '4000(a)1': 'EXPIRED REGISTRATION'}

In [10]:
%%time
# Convert issue date columns to datetime
"""
This step is done in the preprocessing, but when the issue date column is read as object data type when load from local
"""
df['issue_date'] = df['issue_date'].apply(pd.to_datetime)

Wall time: 3min 21s

In [11]:
# Create lat_lon column that contains latitude AND longitude information
df['lat_lon'] = df.apply(lambda x: (x.lat, x.lon), axis=1)
# display(df)

In [12]:
df.dtypes

ticket_number                     int64
issue_date               datetime64[ns]
issue_time                        int64
rp_state_plate                   object
plate_expiry_date               float64
make                             object
body_style                       object
color                            object
location                         object
route                            object
agency                          float64
fine_amount                     float64
agency_desc                      object
color_desc                       object
body_style_desc                  object
violation_code                   object
violation_description            object
meter_id                         object
marked_time                     float64
lat                             float64
lon                             float64
lat_lon                          object
dtype: object

# Aggregation on Location and Different Violation Activities

In [13]:
# Create new column and round lat_lon to 2 decimal place
df['lat_lon_general'] = df.apply(lambda x: ("%.2f" % round(x.lat, 2), "%.2f" % round(x.lon, 2)), axis=1)

In [14]:
# Drop rows with Nan in violation_description column
df = df[df['violation_description'].notna()]
display(df)

,ticket_number,issue_date,issue_time,rp_state_plate,plate_expiry_date,make,body_style,color,location,route,...,color_desc,body_style_desc,violation_code,violation_description,meter_id,marked_time,lat,lon,lat_lon,lat_lon_general
0,4508182571,2020-01-01,228,CA,NaN,VOLK,PA,BK,1729 CLINTON ST,00600,...,BLACK,PASSENGER CAR,80.61,STANDNG IN ALLEY,NaN,NaN,34.072180,-118.262252,"(34.07218011357154, -118.26225236014194)","(34.07, -118.26)"
1,4508195565,2020-01-01,736,CA,NaN,NISS,PA,GY,700 76TH ST W,00500,...,GREY,PASSENGER CAR,22514,FIRE HYDRANT,NaN,NaN,33.970746,-118.285640,"(33.97074616868806, -118.28563960139972)","(33.97, -118.29)"
70,4361778956,2020-01-01,150,CA,202006.0,VOLK,PA,BK,1310 5TH ST W,00611,...,BLACK,PASSENGER CAR,80.56E1,WHITE ZONE,NaN,NaN,34.055142,-118.261988,"(34.05514158548429, -118.26198774811844)","(34.06, -118.26)"
71,4361778960,2020-01-01,204,CA,202001.0,TOYT,PA,GY,1600 7TH ST W,00611,...,GREY,PASSENGER CAR,80.56E4+,RED ZONE,NaN,NaN,34.053894,-118.271141,"(34.05389400030023, -118.27114100109864)","(34.05, -118.27)"
72,4361778971,2020-01-01,226,CA,202005.0,BMW,PA,WT,3037 FUTURE PL,00611,...,WHITE,PASSENGER CAR,80.69B,NO PARKING,NaN,NaN,34.100850,-118.231083,"(34.10084987577322, -118.2310833484698)","(34.10, -118.23)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4993675,4563783313,2023-03-27,2131,CA,202302.0,VOLK,PA,WT,2118 6TH AVE,0205B,...,WHITE,PASSENGER CAR,22500E,BLOCKING DRIVEWAY,NaN,0.0,34.037828,-118.323630,"(34.037828452746886, -118.32363045626128)","(34.04, -118.32)"
4993676,4564468904,2023-03-27,2051,CA,0.0,MERZ,PA,WT,3901 BLUE CANYON DR,350R1,...,WHITE,PASSENGER CAR,80.58L,PREFERENTIAL PARKING,NaN,0.0,34.138853,-118.385230,"(34.138853000459456, -118.38523000623832)","(34.14, -118.39)"
4993677,4563965055,2023-03-27,2227,CA,202401.0,TOYT,PA,BK,15202 VICTORY BLVD,NaN,...,BLACK,PASSENGER CAR,80.61,STANDNG IN ALLEY,NaN,0.0,34.186651,-118.464072,"(34.18665100286754, -118.46407199948064)","(34.19, -118.46)"
4993678,4564298384,2023-03-27,2123,CA,202004.0,NISS,VN,WT,600 PARK ROW DR,NaN,...,WHITE,VAN,80.69B,NO PARKING,NaN,0.0,34.076598,-118.231198,"(34.07659799971699, -118.23119799914352)","(34.08, -118.23)"
4993679,4564603212,2023-03-27,2115,CA,202304.0,CHEV,PA,SL,2331 KELTON AVE,0203A,...,SILVER,PASSENGER CAR,80.58L,PREFERENTIAL PARKING,NaN,0.0,34.040672,-118.431690,"(34.040671795657246, -118.4316901767097)","(34.04, -118.43)"

In [15]:
df_agg = df.groupby([df.issue_date.dt.isocalendar().year, 
                     df.issue_date.dt.isocalendar().week, 
                     df.lat_lon_general, 
                     df.violation_code]).agg({'violation_code': 'count'})
df_agg.columns = ['violation_count']
# display(df_agg)

In [16]:
# Rename axis and flatten the result
df_agg_flat = df_agg.rename_axis(['year', 'week', 
                                  'lat_lon', 'violation_code']).reset_index()

# display(df_agg_flat)

In [17]:
# Pivot table
df_violation_code = df_agg_flat.pivot(index=['year', 'week', 'lat_lon'], 
                                      columns=['violation_code'], 
                                      values='violation_count')
# Reset index and replace NaN
df_violation_code_flat = df_violation_code.reset_index()
df_violation_code_flat.fillna(0, inplace=True)
# display(df_violation_code_flat)

In [18]:
# Filter on year and week
df_violation_code_flat = df_violation_code_flat[df_violation_code_flat['year']==2023]
# df_violation_code_flat = df_violation_code_flat[df_violation_code_flat['week'] >= 8]

In [19]:
# Create column dict to format aggregation
column_name = list(df_violation_code_flat.columns[3:])
agg_dict = {x:'sum' for x in column_name}
# print(agg_dict)

In [20]:
df_violation_code_agg = df_violation_code_flat.groupby(['week', 'lat_lon']).agg(agg_dict)
# display(df_violation_code_agg)

In [21]:
# Reset axis
df_violation_code_agg = df_violation_code_agg.rename_axis(['week', 'lat_lon']).reset_index()
# Rename columns
valid_violation_dict['014'] = 'PARKED IN BUS LOADING ZONE'
valid_violation_dict['000'] = 'PARKING PROHIBITED OR LIMITED'
df_violation_code_agg.rename(columns=valid_violation_dict, inplace=True)
# display(df_violation_code_agg)

In [22]:
# Save to csv
df_violation_code_agg.to_csv('citation_code_aggregation_2023.csv', index=False, encoding='utf-8')