In [1]:
import pandas as pd
from sodapy import Socrata

In [2]:
# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.lacity.org,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

client = Socrata("data.lacity.org",
                 "8JwvqNkTSYSyJhCJckySNhwx4")
socrata_raw = client.get("2nrs-mtv8", limit=700000)
# Convert to pandas DataFrame
df = pd.DataFrame.from_records(socrata_raw)

In [3]:
df.shape

(690454, 28)

In [4]:
df.dtypes

dr_no             object
date_rptd         object
date_occ          object
time_occ          object
area              object
area_name         object
rpt_dist_no       object
part_1_2          object
crm_cd            object
crm_cd_desc       object
mocodes           object
vict_age          object
vict_sex          object
vict_descent      object
premis_cd         object
premis_desc       object
weapon_used_cd    object
weapon_desc       object
status            object
status_desc       object
crm_cd_1          object
location          object
lat               object
lon               object
crm_cd_2          object
cross_street      object
crm_cd_3          object
crm_cd_4          object
dtype: object

In [5]:
df.tail(n=10)

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status,status_desc,crm_cd_1,location,lat,lon,crm_cd_2,cross_street,crm_cd_3,crm_cd_4
690444,230406516,2023-03-19T00:00:00.000,2023-03-19T00:00:00.000,0122,04,Hollenbeck,0488,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510,3200 GARNET ST,34.0248,-118.2076,NaN,NaN,NaN,NaN
690445,230405171,2023-02-05T00:00:00.000,2023-02-02T00:00:00.000,1830,04,Hollenbeck,0428,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,...,IC,Invest Cont,236,3000 BUDAU AV,34.0808,-118.1738,NaN,NaN,NaN,NaN
690446,231405429,2023-02-05T00:00:00.000,2023-02-05T00:00:00.000,1250,14,Pacific,1444,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341,4300 LINCOLN BL,33.9846,-118.4428,NaN,NaN,NaN,NaN
690447,230806871,2023-03-03T00:00:00.000,2023-03-02T00:00:00.000,0620,08,West LA,0889,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354,2000 S HOLT AV,34.0412,-118.3814,NaN,NaN,NaN,NaN
690448,231104474,2023-01-12T00:00:00.000,2023-01-12T00:00:00.000,1240,11,Northeast,1107,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440,1000 MILWAUKEE AV,34.1214,-118.1915,NaN,NaN,NaN,NaN
690449,230804266,2023-01-08T00:00:00.000,2023-01-08T00:00:00.000,1030,08,West LA,0839,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341,10200 SANTA MONICA BL,34.0611,-118.4184,NaN,NaN,NaN,NaN
690450,230109201,2023-03-23T00:00:00.000,2023-03-22T00:00:00.000,1830,01,Central,0111,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440,700 W CESAR E CHAVEZ AV,34.0606,-118.2439,NaN,NaN,NaN,NaN
690451,231604807,2023-01-27T00:00:00.000,2023-01-26T00:00:00.000,1800,16,Foothill,1663,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740,12500 BRANFORD ST,34.2466,-118.4054,NaN,NaN,NaN,NaN
690452,231606525,2023-03-22T00:00:00.000,2023-03-22T00:00:00.000,1000,16,Foothill,1602,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230,12800 FILMORE ST,34.279,-118.4116,NaN,NaN,NaN,NaN
690453,230906458,2023-03-05T00:00:00.000,2023-03-05T00:00:00.000,0900,09,Van Nuys,0914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,14500 HARTLAND ST,34.1951,-118.4487,NaN,NaN,NaN,NaN

In [6]:
# Save dataframe to CSV and work locally from this point
df.to_csv("crime_data_raw.csv", index=False, encoding='utf-8')