In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read preprocessed data
df = pd.read_csv("crime_data_complete.csv")

In [3]:
display(df)

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,crm_cd,crm_cd_desc,mocodes,...,vict_sex,vict_descent,premis_cd,premis_desc,status,status_desc,crm_cd_1,location,lat,lon
0,200100507,2020-01-04,2020-01-04,200,1,Central,101,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 1402,...,M,B,502,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,341,700 BERNARD ST,34.0677,-118.2398
1,201710201,2020-06-19,2020-05-26,1925,17,Devonshire,1708,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1300 0202 0378 0325,...,X,X,203,OTHER BUSINESS,AO,Adult Other,341,11900 BALBOA BL,34.2864,-118.5021
2,200100509,2020-01-04,2020-01-04,2200,1,Central,192,330,BURGLARY FROM VEHICLE,1822 1414 0344 1307,...,M,A,101,STREET,IC,Invest Cont,330,15TH,34.0359,-118.2648
3,200100514,2020-01-05,2020-01-05,1355,1,Central,162,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 2032,...,M,A,503,HOTEL,AA,Adult Arrest,341,800 S OLIVE ST,34.0452,-118.2569
4,200506268,2020-02-22,2020-02-22,1900,5,Harbor,511,440,THEFT PLAIN - PETTY ($950 & UNDER),0319 0344 0429 0448 0305,...,F,W,102,SIDEWALK,IC,Invest Cont,440,PACIFIC COAST,33.7926,-118.3043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306446,230406516,2023-03-19,2023-03-19,122,4,Hollenbeck,488,510,VEHICLE - STOLEN,NaN,...,NaN,NaN,101,STREET,IC,Invest Cont,510,3200 GARNET ST,34.0248,-118.2076
306447,231405429,2023-02-05,2023-02-05,1250,14,Pacific,1444,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0325 0344,...,X,X,402,MARKET,IC,Invest Cont,341,4300 LINCOLN BL,33.9846,-118.4428
306448,231104474,2023-01-12,2023-01-12,1240,11,Northeast,1107,440,THEFT PLAIN - PETTY ($950 & UNDER),1822 0344,...,M,W,101,STREET,IC,Invest Cont,440,1000 MILWAUKEE AV,34.1214,-118.1915
306449,230804266,2023-01-08,2023-01-08,1030,8,West LA,839,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1822,...,M,O,717,HEALTH SPA/GYM,IC,Invest Cont,341,10200 SANTA MONICA BL,34.0611,-118.4184
306450,230109201,2023-03-23,2023-03-22,1830,1,Central,111,440,THEFT PLAIN - PETTY ($950 & UNDER),1602 0344 0346,...,M,B,717,HEALTH SPA/GYM,IC,Invest Cont,440,700 W CESAR E CHAVEZ AV,34.0606,-118.2439

# Analysis on Crime Code

In [4]:
unique_crimecd = df['crm_cd'].unique()
print("Number of unique crime code: ", len(unique_crimecd))

Number of unique crime code:  18

In [5]:
print(unique_crimecd)

[341 330 440 210 310 510 420 350 331 421 320 343 351 520 410 352 433 353]

In [6]:
%%time
# Obtain dictionary for each unique crime code
crimecode_dict = dict()
for code in unique_crimecd:
    try:
        description = df.loc[df['crm_cd'] == code, 'crm_cd_desc'].iloc[0]
        crimecode_dict[code] = description
    except:
        crimecode_dict[code] = ''

Wall time: 14 ms

In [7]:
# Preview crime code and description
crimecode_dict

{341: 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
 330: 'BURGLARY FROM VEHICLE',
 440: 'THEFT PLAIN - PETTY ($950 & UNDER)',
 210: 'ROBBERY',
 310: 'BURGLARY',
 510: 'VEHICLE - STOLEN',
 420: 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
 350: 'THEFT, PERSON',
 331: 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)',
 421: 'THEFT FROM MOTOR VEHICLE - ATTEMPT',
 320: 'BURGLARY, ATTEMPTED',
 343: 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
 351: 'PURSE SNATCHING',
 520: 'VEHICLE - ATTEMPT STOLEN',
 410: 'BURGLARY FROM VEHICLE, ATTEMPTED',
 352: 'PICKPOCKET',
 433: 'DRIVING WITHOUT OWNER CONSENT (DWOC)',
 353: 'DRUNK ROLL'}

In [8]:
# Convert columns to datetime
df[['date_rptd', 'date_occ']] = df[['date_rptd', 'date_occ']].apply(pd.to_datetime)

In [9]:
# Create lat_lon column that contains latitude AND longitude information
df['lat_lon'] = df.apply(lambda x: (x.lat, x.lon), axis=1)

In [10]:
display(df)

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,crm_cd,crm_cd_desc,mocodes,...,vict_descent,premis_cd,premis_desc,status,status_desc,crm_cd_1,location,lat,lon,lat_lon
0,200100507,2020-01-04,2020-01-04,200,1,Central,101,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 1402,...,B,502,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,341,700 BERNARD ST,34.0677,-118.2398,"(34.0677, -118.2398)"
1,201710201,2020-06-19,2020-05-26,1925,17,Devonshire,1708,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1300 0202 0378 0325,...,X,203,OTHER BUSINESS,AO,Adult Other,341,11900 BALBOA BL,34.2864,-118.5021,"(34.2864, -118.5021)"
2,200100509,2020-01-04,2020-01-04,2200,1,Central,192,330,BURGLARY FROM VEHICLE,1822 1414 0344 1307,...,A,101,STREET,IC,Invest Cont,330,15TH,34.0359,-118.2648,"(34.0359, -118.2648)"
3,200100514,2020-01-05,2020-01-05,1355,1,Central,162,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 2032,...,A,503,HOTEL,AA,Adult Arrest,341,800 S OLIVE ST,34.0452,-118.2569,"(34.0452, -118.2569)"
4,200506268,2020-02-22,2020-02-22,1900,5,Harbor,511,440,THEFT PLAIN - PETTY ($950 & UNDER),0319 0344 0429 0448 0305,...,W,102,SIDEWALK,IC,Invest Cont,440,PACIFIC COAST,33.7926,-118.3043,"(33.7926, -118.3043)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306446,230406516,2023-03-19,2023-03-19,122,4,Hollenbeck,488,510,VEHICLE - STOLEN,NaN,...,NaN,101,STREET,IC,Invest Cont,510,3200 GARNET ST,34.0248,-118.2076,"(34.0248, -118.2076)"
306447,231405429,2023-02-05,2023-02-05,1250,14,Pacific,1444,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0325 0344,...,X,402,MARKET,IC,Invest Cont,341,4300 LINCOLN BL,33.9846,-118.4428,"(33.9846, -118.4428)"
306448,231104474,2023-01-12,2023-01-12,1240,11,Northeast,1107,440,THEFT PLAIN - PETTY ($950 & UNDER),1822 0344,...,W,101,STREET,IC,Invest Cont,440,1000 MILWAUKEE AV,34.1214,-118.1915,"(34.1214, -118.1915)"
306449,230804266,2023-01-08,2023-01-08,1030,8,West LA,839,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1822,...,O,717,HEALTH SPA/GYM,IC,Invest Cont,341,10200 SANTA MONICA BL,34.0611,-118.4184,"(34.0611, -118.4184)"
306450,230109201,2023-03-23,2023-03-22,1830,1,Central,111,440,THEFT PLAIN - PETTY ($950 & UNDER),1602 0344 0346,...,B,717,HEALTH SPA/GYM,IC,Invest Cont,440,700 W CESAR E CHAVEZ AV,34.0606,-118.2439,"(34.0606, -118.2439)"

In [11]:
df.dtypes

dr_no                    int64
date_rptd       datetime64[ns]
date_occ        datetime64[ns]
time_occ                 int64
area                     int64
area_name               object
rpt_dist_no              int64
crm_cd                   int64
crm_cd_desc             object
mocodes                 object
vict_age                 int64
vict_sex                object
vict_descent            object
premis_cd                int64
premis_desc             object
status                  object
status_desc             object
crm_cd_1                 int64
location                object
lat                    float64
lon                    float64
lat_lon                 object
dtype: object

# Aggregation on Location and Different Criminal Activities

In [12]:
# Create new column and round lat_lon to 2 decimal place
df['lat_lon_general'] = df.apply(lambda x: ("%.2f" % round(x.lat, 2), "%.2f" % round(x.lon, 2)), axis=1)

In [13]:
display(df)

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,crm_cd,crm_cd_desc,mocodes,...,premis_cd,premis_desc,status,status_desc,crm_cd_1,location,lat,lon,lat_lon,lat_lon_general
0,200100507,2020-01-04,2020-01-04,200,1,Central,101,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 1402,...,502,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,341,700 BERNARD ST,34.0677,-118.2398,"(34.0677, -118.2398)","(34.07, -118.24)"
1,201710201,2020-06-19,2020-05-26,1925,17,Devonshire,1708,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1300 0202 0378 0325,...,203,OTHER BUSINESS,AO,Adult Other,341,11900 BALBOA BL,34.2864,-118.5021,"(34.2864, -118.5021)","(34.29, -118.50)"
2,200100509,2020-01-04,2020-01-04,2200,1,Central,192,330,BURGLARY FROM VEHICLE,1822 1414 0344 1307,...,101,STREET,IC,Invest Cont,330,15TH,34.0359,-118.2648,"(34.0359, -118.2648)","(34.04, -118.26)"
3,200100514,2020-01-05,2020-01-05,1355,1,Central,162,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",1822 0344 2032,...,503,HOTEL,AA,Adult Arrest,341,800 S OLIVE ST,34.0452,-118.2569,"(34.0452, -118.2569)","(34.05, -118.26)"
4,200506268,2020-02-22,2020-02-22,1900,5,Harbor,511,440,THEFT PLAIN - PETTY ($950 & UNDER),0319 0344 0429 0448 0305,...,102,SIDEWALK,IC,Invest Cont,440,PACIFIC COAST,33.7926,-118.3043,"(33.7926, -118.3043)","(33.79, -118.30)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306446,230406516,2023-03-19,2023-03-19,122,4,Hollenbeck,488,510,VEHICLE - STOLEN,NaN,...,101,STREET,IC,Invest Cont,510,3200 GARNET ST,34.0248,-118.2076,"(34.0248, -118.2076)","(34.02, -118.21)"
306447,231405429,2023-02-05,2023-02-05,1250,14,Pacific,1444,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0325 0344,...,402,MARKET,IC,Invest Cont,341,4300 LINCOLN BL,33.9846,-118.4428,"(33.9846, -118.4428)","(33.98, -118.44)"
306448,231104474,2023-01-12,2023-01-12,1240,11,Northeast,1107,440,THEFT PLAIN - PETTY ($950 & UNDER),1822 0344,...,101,STREET,IC,Invest Cont,440,1000 MILWAUKEE AV,34.1214,-118.1915,"(34.1214, -118.1915)","(34.12, -118.19)"
306449,230804266,2023-01-08,2023-01-08,1030,8,West LA,839,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1822,...,717,HEALTH SPA/GYM,IC,Invest Cont,341,10200 SANTA MONICA BL,34.0611,-118.4184,"(34.0611, -118.4184)","(34.06, -118.42)"
306450,230109201,2023-03-23,2023-03-22,1830,1,Central,111,440,THEFT PLAIN - PETTY ($950 & UNDER),1602 0344 0346,...,717,HEALTH SPA/GYM,IC,Invest Cont,440,700 W CESAR E CHAVEZ AV,34.0606,-118.2439,"(34.0606, -118.2439)","(34.06, -118.24)"

In [14]:
df_agg = df.groupby([df.date_occ.dt.isocalendar().year, 
                            df.date_occ.dt.isocalendar().week, 
                            df.lat_lon_general, 
                            df.crm_cd]).agg({'crm_cd': 'count'})

In [15]:
display(df_agg)

                                   crm_cd
year week lat_lon_general  crm_cd
2020 1    (33.71, -118.29) 320          1
          (33.72, -118.29) 210          1
          (33.73, -118.29) 210          1
                           510          3
          (33.73, -118.30) 341          1
...                                   ...
2023 13   (34.22, -118.63) 320          1
          (34.24, -118.41) 510          1
          (34.24, -118.56) 510          1
          (34.26, -118.60) 420          1
          (34.32, -118.43) 310          1

[233464 rows x 1 columns]

In [16]:
df_agg.columns = ['crime_count']
# display(df_agg)

In [17]:
df_agg_flat= df_agg.rename_axis(['year', 'week', 
                                 'lat_lon', 'crime_code']).reset_index().rename(columns={'crm_cd':'crime_count'})
# display(df_agg_flat)

In [18]:
df_crime_code = df_agg_flat.pivot(index=["year", "week", "lat_lon"], columns=['crime_code'], values='crime_count')
# display(df_crime_code)

In [19]:
df_crime_code_flat = df_crime_code.reset_index()
# display(df_crime_code_flat)

In [20]:
# Replace NaN with 0
df_crime_code_flat.fillna(0,inplace=True)

# Filter on year
df_crime_code_flat = df_crime_code_flat[df_crime_code_flat['year']==2023]
# df_crime_code_flat = df_crime_code_flat[df_crime_code_flat['week'] >= 8]

# display(df_crime_code_flat)

In [21]:
column_name = list(df_crime_code_flat.columns[3:])
# print(column_name)
agg_dict = {x:'sum' for x in column_name}
# print(agg_dict)

In [22]:
df_crime_code_agg = df_crime_code_flat.groupby(['week', 'lat_lon']).agg(agg_dict)
# display(df_crime_code_agg)

In [23]:
df_crime_code_agg = df_crime_code_agg.rename_axis(['week', 'lat_lon']).reset_index()

In [24]:
df_crime_code_agg.rename(columns = crimecode_dict, inplace=True)

In [25]:
# Save to csv
df_crime_code_agg.to_csv('crime_code_aggregation_2023.csv', index=False, encoding='utf-8')